
###############################################################################
# 
# DuckDB Julia API - generated C type layer (handles, callbacks, enums)
# 
# !!!!!!!!!!!!
# WARNING: this file is autogenerated from api_spec/v1 by the capigen julia_adapter, manual changes will be overwritten
# Regenerate: capigen julia_adapter --spec-dir api_spec/v1 -o tools/juliapkg/src/api.jl
# It is a sibling of api.jl, written by the same capigen invocation, and is
# included before the hand-written ctypes.jl.
# !!!!!!!!!!!!
#
###############################################################################

const duckdb_thing = Ptr{Cvoid}
const duckdb_thing_delete_t = Ptr{Cvoid}

@enum DUCKDB_COLOR_::Cint begin
    DUCKDB_COLOR_RED = 0
    DUCKDB_COLOR_GREEN = 1
    DUCKDB_COLOR_BLUE = 5
end
const duckdb_color = DUCKDB_COLOR_
