
###############################################################################
# 
# DuckDB Julia API
# 
# !!!!!!!!!!!!
# WARNING: this file is autogenerated from api_spec/v1 by the capigen julia_adapter, manual changes will be overwritten
# Regenerate: capigen julia_adapter --spec-dir api_spec/v1 -o tools/juliapkg/src/api.jl
# !!!!!!!!!!!!
#
###############################################################################

using Base.Libc

if "JULIA_DUCKDB_LIBRARY" in keys(ENV)
    libduckdb = ENV["JULIA_DUCKDB_LIBRARY"]
else
    using DuckDB_jll
end

DUCKDB_API_VERSION = v"1.2.0"


# --------------------------------------------------------------------------------
# Sample
# --------------------------------------------------------------------------------

"""
    duckdb_make_thing()

Creates a thing.

# Arguments

Returns: `duckdb_thing` The new thing.
"""
function duckdb_make_thing()
    return ccall((:duckdb_make_thing, libduckdb), duckdb_thing, ())
end

"""
    duckdb_thing_open(path, out_thing)

Opens a thing from a path.

# Arguments
- `path`: `Cstring` The path to open.
- `out_thing`: `Ref{duckdb_thing}` The resulting thing.

Returns: `duckdb_state` `DuckDBSuccess` on success or `DuckDBError` on failure.
"""
function duckdb_thing_open(path, out_thing)
    return ccall((:duckdb_thing_open, libduckdb), duckdb_state, (Cstring, Ref{duckdb_thing}), path, out_thing)
end

"""
    duckdb_thing_get_column(thing, col)

Gets a column from a thing.

# Arguments
- `thing`: `duckdb_thing` The thing.
- `col`: `idx_t` (1-based index) The column index.

Returns: `Int32` The column value.
"""
function duckdb_thing_get_column(thing, col)
    return ccall((:duckdb_thing_get_column, libduckdb), Int32, (duckdb_thing, idx_t), thing, col - 1)
end

"""
    duckdb_append_blob(appender, data, length)

Appends a blob to a thing.

# Arguments
- `appender`: `duckdb_appender` The appender thing.
- `data`: `Ptr{Cvoid}` The blob data.
- `length`: `idx_t` The number of bytes.

Returns: `duckdb_state` `DuckDBSuccess` on success or `DuckDBError` on failure.
"""
function duckdb_append_blob(appender, data, length)
    return ccall(
        (:duckdb_append_blob, libduckdb),
        duckdb_state,
        (duckdb_appender, Ptr{Cvoid}, idx_t),
        appender,
        data,
        length
    )
end

"""
    duckdb_old_thing(thing)

**DEPRECATION NOTICE**: An old thing. Use make_thing instead.

# Arguments
- `thing`: `duckdb_thing` The thing.

Returns: `Nothing` 
"""
function duckdb_old_thing(thing)
    Base.depwarn("**DEPRECATION NOTICE**: An old thing. Use make_thing instead.", :duckdb_old_thing)
    return ccall((:duckdb_old_thing, libduckdb), Cvoid, (duckdb_thing,), thing)
end

"""
    duckdb_frozen_thing(thing)

**DEPRECATION NOTICE**: A frozen thing carrying deprecation-notice prose but no structured deprecation.

# Arguments
- `thing`: `duckdb_thing` The thing.

Returns: `Nothing` 
"""
function duckdb_frozen_thing(thing)
    return ccall((:duckdb_frozen_thing, libduckdb), Cvoid, (duckdb_thing,), thing)
end





# !!!!!!!!!!!!
# WARNING: this file is autogenerated from api_spec/v1 by the capigen julia_adapter, manual changes will be overwritten
# !!!!!!!!!!!!
